import type { Metadata } from 'next';
import './globals.css';

import localFont from 'next/font/local';
import Gnb from '@/components/Gnb';
import Fnb from '@/components/Fnb';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const pretendard = localFont({
  src: '../assets/fonts/PretendardVariable.woff2',
  display: 'swap',
  variable: '--font-pretendard',
  weight: 'normal',
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={`main-bg ${pretendard.className}`}>
        <Gnb />
        <div>{children}</div>
        {/* <Fnb /> */}
      </body>
    </html>
  );
}
