import type { Metadata } from 'next';
import './globals.css';
import localFont from 'next/font/local';
import ClientLayout from './_component/ClientLayout';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const pretendard = localFont({
  src: '../assets/fonts/PretendardVariable.woff2',
  display: 'swap',
  variable: '--font-pretendard',
  weight: 'normal',
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={`main-bg ${pretendard.className}`}>
        <ClientLayout>{children}</ClientLayout>
      </body>
    </html>
  );
}
